### ISSUE TITLE
Make codebase for FR-FG R10 Risteys

### ISSUE THREAD

**Issue by SaraKuitunen** [dsgelab/risteys#205]
- [ ] various UI updates 
   - [x] 🚩 Update UI content for FR+FG R10 version: naming, title for browser tab text, & links to previous versions & current FG version. done in c500c38, and corrected in 62a1eba4

   - [ ] possibly new color schema, see #139 & #136

   - [x] 🚩 versioning: changelog box for version 2.0.0 (not 2.1.0 as previously planned) (FR+FG R10) & update footer to link correct version. Done in 75e7667f. No need to update footer because v2.0.0 was decided to use for R10, not for R8 beta anymore
  
   - [ ] #131
   
   - [ ] #222
     -  🚩 Vincent: just hide the part of the new docs that are not relevant / need more update
  
   - [x] #193

- [x] 🚩 rebase on master
   - [ ] rebase again

- [x] 🚩 point to a new database #211 

- [x] handle non-core & omitted endpoints
   - [x] see #142 --> will not be done as non-core endpoints != not-omitted endpoints and omit status is used to select endpoints for the analyses
   - [x] pipeline: make a list of omitted endpoints that are excluded from FinRegistry results & import data to DB, #214 
   - [x] #206
   - [x] #220 
   - [x] #215 (not actually a codebase change but part of handling excluded endpoints)

- [ ] Handle _EXALLC and _EXMORE endpoints
   - [x] have control information of endpoints, resolved in bddb859f
   - [x] #213
   - [ ] 🚩 #221 (not possible atm because FR counts are not generated)

- [ ] endpoint definition section with intermediate counts from both projects, #197 (not possible atm because FR counts are not generated)

- [ ] get upset plots from both FR & FG & update codebase to handle files from two projects, #196 (not possible atm because FR upset plots are not generated)
   - [ ] Add project names to the upset plot files and data table files
   - [ ] #141 

- [x] #209 

- [ ] #143 

- [x] update `mix.exs` to have up-to-date application information: update version to be 2.0.0. done in 1af1e2e9 
   
- [x] 🚩new task: #188. **NOTE, this section was added but the 31.1.2023 release 10 doesn't have coloc hits links that open up genes results (overlapping variants and closest genes).**

**Comment by vincent-octo** [comment]
@SaraKuitunen Could you update this task description?

**Comment by vincent-octo** [comment]
Hey @SaraKuitunen , I noticed that #141 is on this tracking issue but is assigned to me.
Would you like to take over #141?

**Comment by SaraKuitunen** [comment]
@vincent-octo, sure, although I don't have clear plans on whether or not to implement (in FR-FG Risteys) and/or how to implement all the points mentioned in #141. So far, in FR-FG Risteys, I've moved upset plots and full data table to their own section and named the section as "Case counts by codes". Maybe we can think about this together in one of our meetings? :)

**Comment by SaraKuitunen** [comment]
I'm closing this issue now as the FinRegistry-FinnGen Risteys R10 was released 31.1.2023 as it was at that time. Not all of the tasks listed in this issue were implemented but they are left here in this issue for possible future reference (or re-opening, if needed). FYI @vincent-octo and @essiviippola :)
