### ISSUE TITLE
Add some meta-stats to lab value distribution in pipeline

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#265]
Add:
- [ ] N People (total of dist)
- [ ] N Records (total of dist)
- [x] N People (total of dataset), for computing the prevalence. Maybe pick N people alive in 2014? Or in 2018 because most of the data comes in only from 2018? Or alive at some point during the study time (2014–2022)?
- [x] bin width, i.e. interval between breaks
  Actually not sure about this one. The easiest for plotting is to just get a list of bin ranges and corresponding y value, so not dealing with bins and breaks separately, and avoiding comparing floating-point numbers which has been the source of many bugs. Though not sure how to make that work with the N>=5 rule. I guess the best way is to get the list of bins computed by polars from the breaks, though not sure if that's even possible if there is no data for a bin?
- [X] % of people having 2 or more tests. This replaces (at least in the frontend) the "Median N measurements / person", since this later stat is very often 1.0, so we could get more insight and differences between lab tests by havin the percentage.
- [x] for the duration data, use year on the time scale instead of days. Because that's what we want to show in the end and it's easier to deal with numbers at source in the pipeline than later in the web app.
- [x] breaks for dist of N measurements / years.
- [x] lab value variability should be output to have the measurement unit along side the bins, otherwise we don't know for which lab val distribution the variability corresponds to.

**Comment by vincent-octo** [comment]
Marking as done for now since most of items are done, and not sure if we need the 2 that are not done. Will re-open if needed.
