### ISSUE TITLE
Investigate weird lab value distributions

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#266]
Fix if the plotting or computing is wrong, not if the underlying data is wrong.

Found:
- [x] [Missing bin](https://github.com/dsgelab/risteys/issues/266#issuecomment-2126517446)
- [x] [Box instead of bins for 706163](https://github.com/dsgelab/risteys/issues/266#issuecomment-2126517622)
- [x] [No bin for 3024561](https://github.com/dsgelab/risteys/issues/266#issuecomment-2132949618)
- [x] [Almost empty bins at regular intervals](https://github.com/dsgelab/risteys/issues/266#issuecomment-2141373945)

**Comment by vincent-octo** [comment]
Missing bin for 3020564
  <img width="700" alt="Screenshot 2024-05-23 at 11 20 29" src="https://github.com/dsgelab/risteys/assets/4919840/e314f979-52df-4ff1-9b17-1cfe3317ca58">

**Comment by vincent-octo** [comment]
Box instead of bins for 706163
  <img width="700" alt="Screenshot 2024-05-23 at 11 21 56" src="https://github.com/dsgelab/risteys/assets/4919840/ebdf506b-25aa-4c84-8382-e3e0afe05973">

**Comment by vincent-octo** [comment]
No bin for 3024561, unit: %

<img width="681" alt="image" src="https://github.com/dsgelab/risteys/assets/4919840/36e45d79-df4b-4b7a-9a81-8707bdb07fcf">
